### ISSUE TITLE
Should this repo have a name like project-template?

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/template#3]

**Comment by tomjemmett** [comment]
the initial intention was to build this up as a general purpose repo to include things like code of conducts etc. If you didn't want to use it as an R-project you just delete the files you don't need

**Comment by Lextuga007** [comment]
Oh yes! Of course, that makes more sense. I think I'll change this issue to add that to the readme. I also found {usethis} has a function for creating Code of Conducts so might use that and reference the Community CoC https://nhs-r-community.github.io/NHSR-way/code-of-conduct.html

**Comment by Lextuga007** [comment]
I've updated the about to say repository from package which was what led me to believe this was specific to packages.
